spring.application.name=ForumService

spring.data.mongodb.uri=mongodb+srv://galinkagross_db_user:esPmODf6lBCaaXaj@cluster0.eix121q.mongodb.net/forumDB?retryWrites=true&w=majority&appName=Cluster0

key.access=2krEIxvIuS1Y4DK0KRcGLfFTB4TlzWjUzgu2OQAxMdU=
key.refresh=2krEIxvIuS1Y4DK0KRcGLfFTB4TlzWjUzgu2OQAxMdU=
